version: '3'

networks:
  converted_in_environment:

services:
  web_server:
    build: .
    container_name: converted_in_web_server
#    command: sh -c "cd /var/www/html && php artisan migrate:fresh --seed"
    depends_on:
      - database_server
    networks:
      - converted_in_environment
    volumes:
      - ./core:/var/www/html
    ports:
      - "8008:80"
    restart: always
  database_server:
    image: mysql
    container_name: converted_in_db_server
    ports:
      - "33066:3306"
    networks:
      - converted_in_environment
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: converted_in